In [15]:

#######################    QUESTION 1     ##########################

ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24]
#1. Sort the list and find the min and max age
#sorting
ages.sort()
#print("sorted ages =",ages)
#minimum
print("min value =",min(ages))
#maximum
print("max value =",max(ages))

#2. Add the min age and the max age again to the list
#adding minimum age to list
ages.insert(0,min(ages))
#adding maximum age to list
ages.insert(-1,max(ages))
print("add min age and max age again to the list =",ages)

#3. Find the median age (one middle item or two middle items divided by two)
#importing statistics to use median
#import statistics
import numpy
#print("median =",statistics.median(ages))
print("median =",numpy.median(ages))
#4. Find the average age (sum of all items divided by their number)
#average =sum/length
#sum
s = sum(ages)
#length
l = len(ages)
#average
average = s/l
print("average =",average)

#5. Find the range of the ages (max minus min)
#range = max-min
range = max(ages)-min(ages)
print("range =",range)


min value = 19
max value = 26
add min age and max age again to the list = [19, 19, 19, 20, 22, 24, 24, 24, 25, 25, 26, 26]
median = 24.0
average = 22.75
range = 7


In [16]:
#######################    QUESTION 2     ##########################
#1. Create an empty dictionary called dog
dog = {}

#2. Add name, color, breed, legs, age to the dog dictionary
dog = {"name" : "Ginger", "color" : "wheat", "breed" : "husk","legs" : 4, "age" : 2.5}

#3. Create a student dictionary and add first_name, last_name, gender, age, 
#   marital status, skills, country, city and address as keys for the dictionary
student = {"first_name" : "Chandana", "last_name" : "G", "gender" : "F", 
           "age" : 25.5, "marital status" : "Single", 
           "skills" : ["Python","Machine Learning","Deep Learning"], 
           "Country" : "USA", "City" : "OP", 
           "Address" : {"street" : "Thomas Jefferson st", "zipcode" : "00000"}}

#4. Get the length of the student dictionary
print(len(student))

#5. Get the value of skills and check the data type, it should be a list
a = student.get("skills")
print(a)
print(type(a))

#6. Modify the skills values by adding one or two skills
student["skills"].append("NLP")
print(student)

#7. Get the dictionary keys as a list
print(list(student.keys()))

#8. Get the dictionary values as a list
print(list(student.values()))


9
['Python', 'Machine Learning', 'Deep Learning']
<class 'list'>
{'first_name': 'Chandana', 'last_name': 'G', 'gender': 'F', 'age': 25.5, 'marital status': 'Single', 'skills': ['Python', 'Machine Learning', 'Deep Learning', 'NLP'], 'Country': 'USA', 'City': 'OP', 'Address': {'street': 'Thomas Jefferson st', 'zipcode': '00000'}}
['first_name', 'last_name', 'gender', 'age', 'marital status', 'skills', 'Country', 'City', 'Address']
['Chandana', 'G', 'F', 25.5, 'Single', ['Python', 'Machine Learning', 'Deep Learning', 'NLP'], 'USA', 'OP', {'street': 'Thomas Jefferson st', 'zipcode': '00000'}]


In [17]:
#######################    QUESTION 3     ##########################
#1. Create a tuple containing names of your sisters and your brothers (imaginary siblings are fine)
sisters = ("Krysten","Emma","Selena")
brothers = ("Edward","Jacob","Richard")
print(sisters)
print(brothers)
#2. Join brothers and sisters tuples and assign it to siblings
siblings = brothers + sisters
print(siblings)
#3. How many siblings do you have?
print(len(siblings))
#4. Modify the siblings tuple and add the name of your father and mother and assign it to family_members
#converting tuple to list
a = list(siblings)
#adding father name
a.append("Romeo")
#adding mother name
a.append("Juliet")
#converting list to tuple & assigning to family_members
family_members = tuple(a)
print(family_members)


('Krysten', 'Emma', 'Selena')
('Edward', 'Jacob', 'Richard')
('Edward', 'Jacob', 'Richard', 'Krysten', 'Emma', 'Selena')
6
('Edward', 'Jacob', 'Richard', 'Krysten', 'Emma', 'Selena', 'Romeo', 'Juliet')


In [18]:
#######################    QUESTION 4     ##########################
it_companies = {'Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle', 'Amazon'}
A = {19, 22, 24, 20, 25, 26}
B = {19, 22, 20, 25, 26, 24, 28, 27}
ages = [22, 19, 24, 25, 26, 24, 25, 24]

#1. Find the length of the set it_companies
print(len(it_companies))


#2. Add 'Twitter' to it_companies
it_companies.add('Twitter')
print(it_companies)

#3. Insert multiple IT companies at once to the set it_companies
it_companies.update(['HP','Honeywell','Cognizant'])
print(it_companies)

#4. Remove one of the companies from the set it_companies
it_companies.pop()
print(it_companies)

#5. What is the difference between remove and discard
print('''remove() and discard() both the methods are used to remove a specific item from the set.
The only difference is remove() method generates error if the specific item is not found in the set whereas
discard() method doesnot give any error if the specific item is not found.''')

#6. Join A and B
#A U B
U = A.union(B)
print(U)

#7. Find A intersection B
I = A.intersection(B)
print(I)

#8. Is A subset of B
print(A.issubset(B))

#9. Are A and B disjoint sets
print(A.isdisjoint(B))
#print(B.isdisjoint(A))

#10. Join A with B and B with A
#A with B
A.update(B)
print(A)
#B with A
B.update(A)
print(B)

#11. What is the symmetric difference between A and B
print(A.symmetric_difference(B))

#12. Delete the sets completely
del it_companies
del A
del B
'''print(it_companies)
print(A)
print(B)'''

#13. Convert the ages to a set and compare the length of the list and the set. 
print(len(ages))
age = set(ages)
print(len(age))
print("Here length of set = 5, where as length of list = 8")

7
{'IBM', 'Google', 'Twitter', 'Microsoft', 'Apple', 'Oracle', 'Facebook', 'Amazon'}
{'HP', 'Honeywell', 'Apple', 'IBM', 'Cognizant', 'Microsoft', 'Facebook', 'Twitter', 'Oracle', 'Google', 'Amazon'}
{'Honeywell', 'Apple', 'IBM', 'Cognizant', 'Microsoft', 'Facebook', 'Twitter', 'Oracle', 'Google', 'Amazon'}
remove() and discard() both the methods are used to remove a specific item from the set.
The only difference is remove() method generates error if the specific item is not found in the set whereas
discard() method doesnot give any error if the specific item is not found.
{19, 20, 22, 24, 25, 26, 27, 28}
{19, 20, 22, 24, 25, 26}
True
False
{19, 20, 22, 24, 25, 26, 27, 28}
{19, 20, 22, 24, 25, 26, 27, 28}
set()
8
5
Here length of set = 5, where as length of list = 8


In [19]:
#######################    QUESTION 5     ##########################
# Given the radius of a circle is 30 meters.
#1. Calculate the area of a circle and assign the value to a variable name of _area_of_circle_
#area of circle = Pi*r*r
pi = 3.14
r = 30 #given
area = pi*r*r
print("_area_of_circle_ =",area)
#2. Calculate the circumference of a circle and assign the value to a variable name of _circum_of_circle_
#circumference of a circle = 2*pi*r
circumference = 2*pi*r
print("_circum_of_circle_ =",circumference)
#3. Take radius as user input and calculate the area
rad = float(input("Enter the circle's radius : "))
area = pi*rad*rad
print(area)

_area_of_circle_ = 2826.0
_circum_of_circle_ = 188.4
28.259999999999998


In [20]:
#######################    QUESTION 6     ##########################
Sent = "I am a teacher and I love to inspire and teach people"
#1. How many unique words have been used in the sentence? Use the split methods and set to get the unique words.
W = set(Sent.split(' ')) #in variable Sent, splitting each word with space seperator i.e., splitting each word at space by making it a set.
print(W)
print(len(W))


{'to', 'teacher', 'love', 'and', 'inspire', 'I', 'a', 'teach', 'people', 'am'}
10


In [21]:
#######################    QUESTION 7     ##########################
#1. Use a tab escape sequence to get the following lines.
'''Name Age Country City
   Asabeneh 250 Finland Helsinki'''
   # \t is the tab escape sequence character
print("Name     \tAge\tCountry \tCity")
print("Asabeneh\t250 \tFinland \tHelsinki")                              
 

Name     	Age	Country 	City
Asabeneh	250 	Finland 	Helsinki


In [22]:
#######################    QUESTION 8     ##########################
"""Given
Use the string formatting method to display the following:
radius = 10
area = 3.14 * radius ** 2
“The area of a circle with radius 10 is 314 meters square.”
"""
radius = 10
area = 3.14 * radius ** 2
text = "The area of a circle with radius {} is {} meters square."
print(text.format(radius,area)) #string format method


The area of a circle with radius 10 is 314.0 meters square.


In [1]:
#######################    QUESTION 9     ##########################
'''Write a program, which reads weights (lbs.) of N students into a list and convert these weights to
kilograms in a separate list using Loop. N: No of students (Read input from user)'''
L = []
L2 = []
N = int(input("Enter no. of students : "))

for i in range(0,N) :
    W = float(input("Enter the weights in lbs: "))  
    W2 = W*0.4535 #conversion from lb to kg
    L.append(W) 
    print("input weight of students in lbs : ",L) #weight in lbs
    L2.append(W2)
    print("weight of students in kgs : ",L2) #weight in kilograms
    
    


input weight of students in lbs :  [2.2]
weight of students in kgs :  [0.9977000000000001]
input weight of students in lbs :  [2.2, 3.2]
weight of students in kgs :  [0.9977000000000001, 1.4512]


In [2]:
#######################    QUESTION 10     ##########################
#1. Divide this data equally into two parts. Use first part as training and second part as testing.
#   Using KNN classifier, for K=3, what would be the predicted outputs for the test samples? Show how you arrived at your answer. 

#importing required libraries
import numpy as np  
#sklearn (scikit learn) is the package of machine learning algorithms
from sklearn.model_selection import train_test_split #for splitting data
from sklearn.neighbors import KNeighborsClassifier #KNN implementation
#datasets from the given graph
p = np.array([[1,0],[2,0],[3,0],[6,0],[6,0],[7,0],[10,0],[11,0]])
#data point classes
q = np.array([0,0,1,1,1,0,0,0])
#splitting the data equally into training and testing
p_train, p_test, q_train, q_test = train_test_split(p,q,test_size = 0.5, random_state = 0, shuffle = False)
print(p_train)
print(q_train)
#KNN implementation
neighbor = KNeighborsClassifier(n_neighbors =3) #k=3
#data fitting (KNN fitting from training data)
neighbor.fit(p_train,q_train)
#predicting output
q_pred = neighbor.predict(p_test)
q_pred

[[1 0]
 [2 0]
 [3 0]
 [6 0]]
[0 0 1 1]


array([1, 1, 1, 1])

In [3]:
#2. Compute the confusion matrix for this and calculate accuracy, sensitivity and specificity values. 
#importing confusion matrix
from sklearn.metrics import confusion_matrix
#test class labels comparison with predicted class labels
confusion_matrix(q_test,q_pred)
#acc_score = accuracy_score(q_test, q_pred)

array([[0, 3],
       [0, 1]], dtype=int64)